[project]
name = "character-voicevox-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.6",
    "httpx>=0.28.1",
    "pydantic>=2.10.4",
    "uvicorn>=0.34.0",
]
